# permissions for end users to edit podannotators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podannotator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: annotation-controller
    app.kubernetes.io/part-of: annotation-controller
    app.kubernetes.io/managed-by: kustomize
  name: podannotator-editor-role
rules:
- apiGroups:
  - annotate.example.com
  resources:
  - podannotators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - annotate.example.com
  resources:
  - podannotators/status
  verbs:
  - get
